# Generated by Django 3.2.6 on 2021-08-06 19:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0004_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetails',
            name='name',
            field=models.CharField(default='', max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-Z]+$')]),
        ),
    ]
