# Generated by Django 3.2.6 on 2021-08-07 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0008_alter_employeedetails_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetails',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
